// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Variables producción (usadas si .env no está o tiene placeholders).
// Proyecto real de esta app: nrlawnrmxlipizjwebbz (3Ws-luz), el único que contiene
// el esquema de colaboradores. NO usar kamfdjczamfgumkiwjpw (3Ws): es un proyecto
// antiguo sin esas tablas y caer en él rompería las funciones de colaboradores.
const DEFAULT_SUPABASE_URL = "https://nrlawnrmxlipizjwebbz.supabase.co";
const DEFAULT_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ybGF3bnJteGxpcGl6andlYmJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTEwNTUsImV4cCI6MjA3MzE4NzA1NX0.5SJK-kc56fuJDpiy8NxYlSry5Uz2vrwwKAHK4UUY6Ck";

const envUrl = import.meta.env.VITE_SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
// Si .env.local tiene placeholders, usar valores por defecto para que la subida funcione en local
const isPlaceholderUrl = typeof envUrl === 'string' && (envUrl.includes('TU_PROYECTO') || !envUrl.includes('supabase.co'));
const isPlaceholderKey = typeof envKey === 'string' && (envKey.length < 100 || envKey.includes('aquí') || envKey.includes('tu_'));
const SUPABASE_URL = !isPlaceholderUrl && envUrl ? envUrl : DEFAULT_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = !isPlaceholderKey && envKey ? envKey : DEFAULT_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/** Referencia del proyecto (subdominio *.supabase.co). Debe coincidir con el que ves en dashboard.supabase.com al revisar tablas. */
export const SUPABASE_PROJECT_REF = (() => {
  try {
    const host = new URL(SUPABASE_URL).hostname;
    return host.replace('.supabase.co', '');
  } catch {
    return null;
  }
})();

if (import.meta.env.DEV) {
  console.info(
    '[Supabase] La app usa el proyecto:',
    SUPABASE_PROJECT_REF ?? SUPABASE_URL,
    '— al buscar clientes en el panel, abre este mismo proyecto.',
  );
}